#ifndef SYMBOLEDITOR_GLOBAL_H
#define SYMBOLEDITOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SYMBOLEDITOR_LIBRARY)
#  define SYMBOLEDITORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SYMBOLEDITORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SYMBOLEDITOR_GLOBAL_H
